fixes for AutoDoc
now unit tests are failing

```
$ vendor/bin/phpunit
PHPUnit 5.5.4 by Sebastian Bergmann and contributors.

....
Fatal error: Class 'Jcupitt\Vips\AutoDocs' not found in
/home/john/GIT/php-vips/src/Image.php on line 410
```

 Changes to be committed: